### ISSUE TITLE
How to use with temporal

### ISSUE THREAD

**Issue by graid2030** [spiral/roadrunner-laravel#100]
I tried to use `Mode::MODE_TEMPORAL => \Temporal\Worker\Worker::class,` in config/roadrunner.php -> workers
but constructor not сompatible, also I can not use closure with \Temporal\WorkerFactory::newWorker()

**Comment by graid2030** [comment]
temporal/sdk v1.3.6
, thank you

**Comment by macielcr7** [comment]
I have the same problem, how should I implement the temporal? @graid2030 @tarampampam
