### ISSUE TITLE
Laravel drivers for queue and kv

### ISSUE THREAD

**Issue by pvs9** [spiral/roadrunner-laravel#101]
Hi, @tarampampam. Is there a plan to implement larval drivers for RR KV and jobs module? It would be very useful, or, maybe, some samples you tried to implement. Thanks!

**Comment by tarampampam** [comment]
Hi @pvs9!

Currently, I have no plans to implement them (sorry for this, but I haven't enough free time for this) but would be great if someone (like you) make a Pull Request with a working solution or a separate package for this!
