### ISSUE TITLE
laravel pagination always returning the first page (laravel as api backend)

### ISSUE THREAD

**Issue by XiDanko** [spiral/roadrunner-laravel#104]
## Describe the bug

> A clear and concise description of what the bug is.

### Expected behaviour

> Tell us what should happen.

### Actual behaviour

> Tell us what happens instead.

### Steps to reproduce

> Describe steps to behavior reproducing.

## System information

> Please, complete the following information:

Key                     | Value
----------------------- | ----
PHP version             | 
Current package version | 
RoadRunner version      | 
Environment             | 

### RoadRunner configuration file content

```yaml
# Paste here your `.rr.yaml` file content
```

### Package configuration file content

```php
# Paste here your `config/roadrunner.php` file content
```

## Additional context

> Add any other context about the problem here.

**Comment by tarampampam** [comment]
Please fill out the issue according to the template

**Comment by tarampampam** [comment]
I will open your issue back when you provide all the required information 👍🏼
