### ISSUE TITLE
How to deploy on AWS?

### ISSUE THREAD

**Issue by ant100** [spiral/roadrunner-laravel#11]
> If you have any questions feel free to ask

Hi, I feel dumb for asking this but I'm not sure where else to ask it. I managed to successfully deploy my laravel application with roadrunner, but now I want to go into production. Up until now I've been using the following command to start the server:

`./rr -c ./.rr.yaml serve -d`

I've tried the same command via putty to my EC2 instance and it's working. However, when I close my putty connection, the server also shuts down.

Is there a way to enable Roadrunner and keep it running?

**Comment by tarampampam** [comment]
Run `rr` as a daemon? If you do not use containers (like docker), you can run it using `systemd`, `supervisord` or any other on your choice.

**Comment by wolfy-j** [comment]
Take a look at this configuration to run RR as service: https://github.com/spiral/roadrunner/tree/master/systemd

**Comment by ant100** [comment]
> Take a look at this configuration to run RR as service: https://github.com/spiral/roadrunner/tree/master/systemd

Oh, thanks a lot!! I'm using that file and also following https://roadrunner.dev/docs/beep-beep-systemd

However I'm getting `Unit rr.service could not be found.` error 

I updated the rr.service file as following:

`[Unit]`
`Description=High-performance PHP application server`

`[Service]`
`Type=simple`
`ExecStart=/home/ubuntu/rr-laravel/public/rr serve -d -c /home/ubuntu/rr-laravel/public/.rr.yaml`
`Restart=always`
`RestartSec=30`

`[Install]`
`WantedBy=default.target`

**Comment by wolfy-j** [comment]
Did you register the service? Did you get any error while doing so?

**Comment by ant100** [comment]
When I tried 
`systemctl enable --user rr.service`
I got the same error of could not be found.

But, when I tried
`systemctl enable --user /home/ubuntu/ann/rr-laravel/public/vendor/spiral/roadrunner/systemd/rr.service`
I got no response.

However, after that, I typed the start command but, when typing the full path like this:
`sudo systemctl start /home/ubuntu/ann/rr-laravel/public/vendor/spiral/roadrunner/systemd/rr.service`

I get a different error:
`Failed to start home-ubuntu-ann-rr\x2dlaravel-public-vendor-spiral-roadrunner-systemd-rr.service.mount: Unit home-ubuntu-ann-rr\x2dlaravel-public-vendor-spiral-roadrunner-systemd-rr.service.mount not found.`

**Comment by ant100** [comment]
I got it to work, had to copy the service to my /etc/systemd/system directory. However, the server is not working.  Maybe there's something wrong with this line?

`ExecStart=/home/ubuntu/rr-laravel/public/rr serve -d -c /home/ubuntu/rr-laravel/public/.rr.yaml`

I'm using the path to rr that's in my application folder and the .rr.yaml as well.
