### ISSUE TITLE
Pcov || XDebug with RR

### ISSUE THREAD

**Issue by eldario** [spiral/roadrunner-laravel#113]
Hello!

### Is your feature request related to a problem?

It is noted in the `Dockerfile` that `xdebug` is supposed to be used. But there are no settings for the `RoadRunner`.

### Describe the solution you'd like

- If `xdebug` is only used to cover code with tests, it may be possible to use `pcov` instead?
- Or maybe add documentation with examples on using the `RoadRunner` with `xdebug`?

## Additional context

RR with debug: https://roadrunner.dev/docs/php-debugging
[Pcov](https://github.com/krakjoe/pcov) is built for PHPUnit code coverage not **something else**.

**Comment by tarampampam** [comment]
Hi there! Xdebug is used only for internal test coverage calculation, not more. Are you sure this is a relevant repository for your question?  :)

**Comment by eldario** [comment]
> Are you sure this is a relevant repository for your question?

Yes.

**Comment by tarampampam** [comment]
Ok, is this affects RR integration with Laravel? 😄

**Comment by eldario** [comment]
yes, I mixed up the repositories 😵‍💫

**Comment by eldario** [comment]
@tarampampam close it, thank you
