### ISSUE TITLE
To support php 8.2

### ISSUE THREAD

**Issue by jskorlol** [spiral/roadrunner-laravel#114]
I have a problem using it in php 8.2.

```
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/vendor/spiral/roadrunner-laravel/src/Console/Commands/WorkerFactory.php on line 59
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/vendor/spiral/roadrunner-laravel/src/Console/Commands/WorkerFactory.php on line 63
```

https://github.com/spiral/roadrunner-laravel/blob/master/src/Console/Commands/WorkerFactory.php#L59
https://github.com/spiral/roadrunner-laravel/blob/master/src/Console/Commands/WorkerFactory.php#L63

https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated

I have that problem.

Any chance of supporting PHP 8.2?

**Comment by tarampampam** [comment]
Yes, sure! I will make a fix tomorrow, okay?
