### ISSUE TITLE
How ican use this with caddy webserver

### ISSUE THREAD

**Issue by vahidalvandi** [spiral/roadrunner-laravel#119]
> If you have any questions feel free to ask
How ican use this with caddy webserver

**Comment by tarampampam** [comment]
Could you explain what exactly you mean?

**Comment by vahidalvandi** [comment]
I use caddy insted of ngnix . Because caddy have ssl in native

**Comment by tarampampam** [comment]
You can use any proxy server in front of the RoadRunner, of course 😄 
Or do you have a problem with it?

**Comment by vahidalvandi** [comment]
Just As I researched, is roadrunner just an alternative to php-fpm?  And if I send the docker file of my project, would it help you to make it work with roadrunner?

**Comment by tarampampam** [comment]
Not quite like that. RoadRunner is the application server at first, it means you do need an Nginx or something like that to serve the HTTP requests - RR does it yourself out of the box. All that you may need is a proxy server for automatic SSL certs (with the requests proxying to the RR) kinda Caddy, Traefik, Nginx + certbot, or something like that on your choice.

About your second question - did you look here? https://github.com/tarampampam/laravel-roadrunner-in-docker

**Comment by tarampampam** [comment]
Can I close this issue?

**Comment by vahidalvandi** [comment]
I was confused. Do you think I can have caddy or ngnix like before and use the reverse proxy method from the roadrunner port?

**Comment by vahidalvandi** [comment]
Thank you I work it
