### ISSUE TITLE
How to configure Auth0?

### ISSUE THREAD

**Issue by ant100** [spiral/roadrunner-laravel#12]
> If you have any questions feel free to ask

Hi, me again. I'm currently running an application on Laravel and have sucessfully configured roadrunner-laravel, however my application is using Auth0 authentication. 

Is there an easy way to configure auth0? Or at least some documentation or pointers on what should I configure in order for it to work?

The error I'm getting is:

```
InvalidArgumentException
Authentication user provider [auth0] is not defined. 
```

**Comment by tarampampam** [comment]
Glad to see you again! It seems like wrong configuration in your application, not `roadrunner`/`roadrunner-laravel` issue.

So, take look into Auth providers docs: <https://laravel.com/docs/7.x/authentication>

> Also you must remember - auth providers usually [must be reseted](https://github.com/spiral/roadrunner-laravel/blob/v3.5.0/config/roadrunner.php#L130) on each request.

**Comment by ant100** [comment]
> So, take look into Auth providers docs: https://laravel.com/docs/7.x/authentication 

I did! It's strange because I'm also running the same application on a apache server and it's working fine there

>  Also you must remember - auth providers usually [must be reseted](https://github.com/spiral/roadrunner-laravel/blob/v3.5.0/config/roadrunner.php#L130) on each request.

Ah, I didn't know this! Is there an additional configuration that must be done? I included the path to my AuthServiceProvider class in that config file.

**Comment by tarampampam** [comment]
Usually not. You can try to set environment variable `APP_REFRESH` to `true`, and if in this case all will be fine - problem likely on providers initialization steps. Can you show source code of service provider for `auth0`?

**Comment by ant100** [comment]
> Usually not. You can try to set environment variable `APP_REFRESH` to `true`, and if in this case all will be fine - problem likely on providers initialization steps. 

Just tried this, but it wasn't fixed :(

> Can you show source code of service provider for `auth0`?

Sure! Also, I don't know if this helps but I've followed step by step this guide to install auth0 provider https://auth0.com/docs/quickstart/webapp/laravel/01-login

This is my Custom User Handler that connects to my application database to store the auth0 user:
[CustomUserRepository.txt](https://github.com/spiral/roadrunner-laravel/files/4944008/CustomUserRepository.txt)

And this is Auth0Service class I found in `\vendor\auth0\login\src\Auth0Service.php`
[Auth0Service.txt](https://github.com/spiral/roadrunner-laravel/files/4944009/Auth0Service.txt)

I'm not sure if these are the files you asked for.

**Comment by tarampampam** [comment]
Also can you attach full stacktrace of exception?

[`auth0` service provider](https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/LoginServiceProvider.php) seems ok.

Are you shure about `Auth0\Login\LoginServiceProvider::class` is in `config/roadrunner.php['reset_providers']` and `auth0` is in `config/roadrunner.php['clear_instances']`?

With `php artisan serve --port=8080` app works as expected?

**Comment by tarampampam** [comment]
@eldario friendly ping

**Comment by ant100** [comment]
> Are you shure about `Auth0\Login\LoginServiceProvider::class` is in `config/roadrunner.php['reset_providers']` and `auth0` is in `config/roadrunner.php['clear_instances']`?

They weren't but I have added them! And now I'm getting a new exception:

`Argument 1 passed to Auth0\Login\Repository\Auth0UserRepository::getUserByUserInfo() must be of the type array, null given, called in /home/ubuntu/html/rirt/vendor/auth0/login/src/controllers/Auth0Controller.php on line 37`

I was working locally when I got that error, so I decided to also try it in a EC2 Instance, and I'm getting the same exception.

> With `php artisan serve --port=8080` app works as expected?

Yes, I was able to render the login page and correctly authenticate to the login panel with php artisan serve at port 8080


I tried to share the stack trace with Flare but I get an error.

**Comment by tarampampam** [comment]
One more try - add into `config/roadrunner.php['clear_instances']` next lines above `auth0`:
- `'auth'`
- `'auth.driver'`
- `Illuminate\Contracts\Auth\Access\Gate::class`
- `'cookie'`
- `'session'`
- `'session.store'`
- `Illuminate\Session\Middleware\StartSession::class`
- `\Auth0\Login\Auth0Service::class`

**Comment by eldario** [comment]
@ant100 
As a result, we found some problems that contribute to the fact that an exception is thrown. We are currently working on a solution.

**Comment by eldario** [comment]
Or, you can apply another solution:

1. Create your own controller that will extend the vendor `\Auth0\Login\Auth0Controller`
2. Override method with these lines:
```php
/**
  * Callback action that should be called by auth0, logs the user in.
*/
public function callback()
{
    $_GET['code']  = $request->get('code');
    $_GET['state'] = $request->get('state');

    // rest of code
}
```
3. And don't forget to change namespace for new controller in `routes/web.php`

Try this and write about success

**Comment by ant100** [comment]
@eldario 
Thank you so much for your help! I follow your steps, but I'm getting a `Undefined variable: request` error, this is because I don't have the $request variable set in your code. Should I be instantiating it somewhere? 
> ```
> /**
>   * Callback action that should be called by auth0, logs the user in.
> */
> public function callback()
> {
>     $_GET['code']  = $request->get('code');
>     $_GET['state'] = $request->get('state');
> 
>     // rest of code
> }
> ```

**Comment by eldario** [comment]
@ant100 
This already sounds great!

I can suggest to do like this:
1. Create **new method** in your controller, use dependency injection, change method name in `routes/web.php`
```php
    /**
     * @param Request $request
     *
     * @return mixed
     */
    public function ownCallbackMethod(Request $request)
    {
        $_GET['code']  = $request->get('code');
        $_GET['state'] = $request->get('state');

        return parent::callback();
    }
```
2. Use Laravel helper `request()`.
```php
    /**
     * @return mixed
     */
    public function callback()
    {
        $_GET['code']  = request()->get('code');
        $_GET['state'] = request()->get('state');

        return parent::callback();
    }
```


Try this and write about success

**Comment by ant100** [comment]
@eldario 

**Really close now!** I got two different results:

- On my local machine, I get a 

```
Auth0\SDK\Exception\CoreException
Invalid state
```
I have tried deleting cookies and even on incognito mode, but still every time I try to login I get the same exception.

- However, I also tried it on a live EC2 Instance, and the login actually worked! The issue now is that all my assets on my public directory are returning Laravel's 404 not found. 

For instance: http://ec2-3-81-33-29.compute-1.amazonaws.com:8080/css/app.css

I'm not sure why this is happening, the route seems to be well formed

**Comment by tarampampam** [comment]
@ant100 sorry, but we have no enough time for helping with 3rd party solutions. So, if you will have problems with rr or this package - please, open a new issue, and we will glad to help you!

If you will solve the problem on your own, please describe how you did it to help others.

**Comment by ant100** [comment]
@tarampampam I understand, but like I mentioned I don't have any problems when running the same application on Apache or even php artisan serve, which is why it seems like an issue with roadrunner-laravel issue.
