### ISSUE TITLE
Register service provider?

### ISSUE THREAD

**Issue by koteezy** [spiral/roadrunner-laravel#15]
Hello Laravel experts!

In our application, we use JWT authorization, and previously on laravel (not RR), we simpy use: https://github.com/tymondesigns/jwt-auth

But when we move to RR, we get some errors, like:
```
Auth driver [jwt] for guard [api] is not defined.
```

We fix this error moving ```\Tymon\JWTAuth\Providers\LaravelServiceProvider::class``` from app.php ( providers block ) to roadrunner.php ( reset_providers block), but, recently we noticed that this causes a memory leak. Even on Hello world responses, any ideas, how we can register it normally without memory leak?

**Comment by tarampampam** [comment]
Hi @koteezy!

Memory leaks on 3rd party packages must be detected and fixed on packages side. Another way - write your own service provider for required package and try to fix it by yourself.

A quick look at [AbstractServiceProvider.php](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/AbstractServiceProvider.php) and [LaravelServiceProvider.php](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/LaravelServiceProvider.php) shows that their uses a lot of `$this->app->singleton(...)` and _maybe_ you should add all of it (or service provider class) into [clear_instances](https://github.com/spiral/roadrunner-laravel/blob/v3.5.0/config/roadrunner.php#L114) section - maybe this can helps you.

**Comment by koteezy** [comment]
@tarampampam clear_instances not works for me, but thanks anyway! 

If in future someone will need fix, i simply create a service provider, and remove necessary lines, which caused a memory leak.

<details>
  <summary>CustomJwtServiceProvider</summary>
  
```
<?php

namespace App\Providers\Auth;

use Tymon\JWTAuth\Providers\AbstractServiceProvider;

class CustomJwtServiceProvider extends AbstractServiceProvider
{
    /**
     * {@inheritdoc}
     */
    public function boot () {
        $this->aliasMiddleware();

        $this->extendAuthGuard();
    }

    public function register () {
        $this->registerAliases();

        $this->registerJWTProvider();
        $this->registerAuthProvider();
        $this->registerStorageProvider();
        $this->registerJWTBlacklist();

        $this->registerManager();
        $this->registerTokenParser();

        $this->registerJWT();
        $this->registerJWTAuth();
        $this->registerPayloadValidator();

        $this->registerClaimFactory();
        $this->registerPayloadFactory();
        $this->registerJWTCommand();
    }

    /**
     * {@inheritdoc}
     */
    protected function registerStorageProvider () {
        $this->app->singleton( 'tymon.jwt.provider.storage', function () {
            $instance = $this->getConfigInstance( 'providers.storage' );

            if ( method_exists( $instance, 'setLaravelVersion' ) ) {
                $instance->setLaravelVersion( $this->app->version() );
            }

            return $instance;
        } );
    }

    /**
     * Alias the middleware.
     *
     * @return void
     */
    protected function aliasMiddleware () {
        $router = $this->app[ 'router' ];

        $method = method_exists( $router, 'aliasMiddleware' ) ? 'aliasMiddleware' : 'middleware';

        foreach ( $this->middlewareAliases as $alias => $middleware ) {
            $router->$method( $alias, $middleware );
        }
    }
}

```
  
</details>

**Comment by tarampampam** [comment]
@ErriourRU Could you please test [this solution](https://github.com/tymondesigns/jwt-auth/issues/2113#issuecomment-898684846)?

Because of [tymon/jwt-auth](https://github.com/tymondesigns/jwt-auth) package looks abandoned and cannot be used with PHP 8 & fresh Laravel - I can't provide a custom listener for his state resetting, sorry for that :(

**Comment by leon0399** [comment]
@tarampampam right now we are working on [fork ](https://github.com/PHP-Open-Source-Saver/jwt-auth)of this repository and trying to fix existing issuer

According to my tests, solution you stated is not sufficient, and some changes to library required. I created an issue on this and we will fix it soon
