### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by falke2** [spiral/roadrunner-laravel#17]
Hello.
Set up fresh laravel installation.
Made `.rr.yaml` file with example config provided here and trying to start rr with `./rr.exe -c ./.rr.yaml serve -d` on windows or `./rr -c ./.rr.yaml serve -d` on WSL2 but both gives me an error `ERRO[0000] [http]: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1
Error: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1`

**Comment by falke2** [comment]
Executing worker directly gives this output:
```dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../spiral/roadrunner-laravel/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/rr-worker" "$@"```

**Comment by tarampampam** [comment]
It looks like `echo`, `print`, `printf`, `dump`, `dd` or similar functions is used in your application

**Comment by falke2** [comment]
Thing is it's clear laravel installation without any additions or my code

**Comment by tarampampam** [comment]
In this case, please, close this issue and open one more with `Bug report` type (and fill up all fields, please)

**Comment by tarampampam** [comment]
And one more question - can you reproduce this error using linux or docker environment? I have no windows for reproducing described behavior

**Comment by falke2** [comment]
WSL2 should be enough i think
