### ISSUE TITLE
Should this bridge also work with Lumen?

### ISSUE THREAD

**Issue by andrei-dascalu** [spiral/roadrunner-laravel#18]
Hello,

I'm wondering if this is expected to also work with Lumen framework with Laravel components. I'm asking because I've been trying to find a working bridge for Lumen.

I've tried setting this up with Lumen 8 but after installing `laravelista/lumen-vendor-publish` when I try to use the publish commands, I get this:

```
    php artisan vendor:publish --provider='Spiral\RoadRunnerLaravel\ServiceProvider' --tag=config
   > Unable to locate publishable resources.
```

**Comment by tarampampam** [comment]
Hi @andrei-dascalu!

Attempt to integrate with lumen [was here](https://github.com/avto-dev/roadrunner-laravel/pull/40/files), but without successful result. Currently we have no integrations plans.

**Comment by andrei-dascalu** [comment]
@tarampampam thanks! indeed, once I got past the configuration publishing i saw some of the potential integration pitfalls.
