### ISSUE TITLE
Is it possible to install on Windows? Without wsl, docker.

### ISSUE THREAD

**Issue by darakanoit** [spiral/roadrunner-laravel#19]
Clean laravel project.
I did it according to the instructions, "rr -c rr.yaml serve -d"
outputs WARN [0000] config: open D: \ projects \ b \ rr.yaml: The system cannot find the file specified.
If you run "rr serve"
ERRO [0000] [http]: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1
Error: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1
Is it possible to paint detailed instructions? What am I doing wrong? The same spiral framework and roadrunner worked well with Windows.

**Comment by tarampampam** [comment]
Please, use WSL or [cygwin](https://www.cygwin.com/)

**Comment by darakanoit** [comment]
A problem was found.
Under Windows, you need to run the command through
command: 'php vendor / spiral / roadrunner-laravel / bin / rr-worker'
because command: 'php vendor / bin / rr-worker' and command: 'php vendor / bin / rr-worker.bat' fall into stdout error. The discussion was in a discord chat.
Please make a note in the documentation that Windows users should specify command: 'php vendor / spiral / roadrunner-laravel / bin / rr-worker' in the.

**Comment by darakanoit** [comment]
Please provide notes for Windows users. If necessary, I can provide an updated readme.md

**Comment by tarampampam** [comment]
It will be great! :+1:

**Comment by darakanoit** [comment]
This is my first open source PR. Sorry for any mistakes.
I suggest further improving the documentation and developing the package.
I was interested in the features of the spiral framework for laravel - in-memory jobs (queues) and others.
