### ISSUE TITLE
Suggestion to Replace the command on publish config

### ISSUE THREAD

**Issue by daison12006013** [spiral/roadrunner-laravel#20]
From the published config of `.rr.yaml.dist`

```
workers:
    command:  "php psr-worker.php pipes"
```

I suggests to replace the command to be `php ./vendor/bin/rr-worker pipes`

This will avoid confusion with new people who'd like to try it out.

**Comment by tarampampam** [comment]
`rr-worker` does not supports any arguments (now), so - for what?

**Comment by darakanoit** [comment]
This is a standard config in the RR, it is not necessary to publish it. There is an example of the required config in the documentation.

**Comment by daison12006013** [comment]
@darakanoit I'm not following, then the -artisan publish command inside the readme is a **false positive**?

Try to install a fresh one and publish the config, you guys can see what I meant.
