### ISSUE TITLE
Question about GRPC server

### ISSUE THREAD

**Issue by vanushwashere** [spiral/roadrunner-laravel#29]
How can I integrate [grpc server](https://github.com/spiral/php-grpc) into this ?

**Comment by tarampampam** [comment]
This package contains only bridge between RR and Laravel framework. Maybe you want to ask this in [spiral/roadrunner](https://github.com/spiral/roadrunner) repository?

**Comment by tarampampam** [comment]
Issue can be closed?

**Comment by vanushwashere** [comment]
so, I cannot run GRPC server using only this bridge?

**Comment by wolfy-j** [comment]
I found this implementation - https://github.com/roseffendi/laravel-grpc-server 

As far I can see it has a bunch of extra setup.

**Comment by vanushwashere** [comment]
Thx, will try

**Comment by dac-humi** [comment]
I got something working here: https://github.com/laravel/octane/issues/561

Ticket closed with kind words of encouragement. Unlikely to be supported. 

Easier to start with: https://github.com/spiral/app-grpc
