### ISSUE TITLE
listen unix /var/run/rr-rpc.sock: bind: permission denied

### ISSUE THREAD

**Issue by semprul57** [spiral/roadrunner-laravel#36]
> If you have any questions feel free to ask

I've tried to use roadrunner-laravel and follow the example instruction to run the worker and create relay in `/var/run/rr-rpc.sock` but i got permission denied because `/var/run` are owned by root

after that i tried to run as super user but all the generated session file is owned by root and cause some of the function not worked properly like database connection, etc

is there any solution for this issue?

**Comment by tarampampam** [comment]
Hi @semprul57!

You can run `rr` process as a user, which can create a file inside `/var/run` directory **and** use an unprivileged user for a worker processes:

https://github.com/spiral/roadrunner-binary/blob/3eeefb48d27084bc63474da09735feb583344a3b/.rr.yaml#L27-L35

Another way - change path to the socket to `/tmp/rr-rpc.sock`.

**Comment by semprul57** [comment]
Thank you very much for your help, i've tried to add my user & group but still got the permission issues but for the `/tmp/rr-rpc.sock` is running smoothly.

Thank you
