### ISSUE TITLE
rr-grpc & rr can't work together

### ISSUE THREAD

**Issue by xuqihua** [spiral/roadrunner-laravel#38]
When composer.json add the require below ,the packages can install ,but  the command  `rr serve -d` can't work  
"spiral/php-grpc": "^1.0",
"spiral/roadrunner-laravel": "^3.0"

When composer.json add the require below ,the dependencies conflict
"spiral/php-grpc": "^1.0",
"spiral/roadrunner-laravel": "^4.0"

**Comment by tarampampam** [comment]
Could you please provide logs, PHP, and RR versions?

**Comment by xuqihua** [comment]
> Could you please provide logs, PHP, and RR versions?

PHP 7.4.11
rr version 2.0.4


`Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install spiral/roadrunner-laravel v4.0.1 (conflict analysis result)
    - Conclusion: install spiral/roadrunner v1.5.1 (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.8.0], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/goridge[v2.4.3, v2.4.4, v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.0.2 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.0.3 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.0.4 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.0.5 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.1.0 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.1.1 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.1.2 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.1.3 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.1.4 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.2.0 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.2.1 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.3.0 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.3.2 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.3.3 (conflict analysis result)
    - Conclusion: don't install one of spiral/goridge[v3.0.0], spiral/roadrunner[v1.5.1] | install one of spiral/goridge[2.4.0, ..., v2.4.5] (conflict analysis result)
    - Conclusion: don't install spiral/goridge 2.4.0 (conflict analysis result)
    - Conclusion: don't install spiral/goridge 2.4.1 (conflict analysis result)
    - Conclusion: don't install spiral/roadrunner-worker v2.0.3 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.4.2 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.4.3 (conflict analysis result)
    - Conclusion: don't install spiral/goridge v2.4.4 (conflict analysis result)
    - Conclusion: don't install one of spiral/goridge[v2.4.5], spiral/roadrunner-laravel[v4.0.0] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.7.0], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.6.4], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.6.3], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.6.2], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.7.1], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-laravel[v4.0.1], spiral/php-grpc[v1.2.0] | install one of spiral/roadrunner[v1.4.0, ..., v1.9.2], spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.3], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.4], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.7.0], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.7.1], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.2, v2.0.3], spiral/goridge[v3.0.0-beta1, ..., 3.1.x-dev (alias of dev-master)] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.1] | install one of spiral/goridge[v2.0.2, ..., v2.4.5, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.0] | install one of spiral/goridge[v2.0.2, ..., v2.4.5, v3.0.0-beta3, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.5.3] | install one of spiral/goridge[v2.0.2, ..., v2.4.5, v3.0.0-beta2, ..., v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.2], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.1], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.4] | install one of spiral/goridge[v2.0.2, ..., v2.4.5, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.3] | install one of spiral/goridge[v2.0.2, ..., v2.4.5, v3.0.0-beta3, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.5.3], spiral/roadrunner-laravel[v4.0.1] | install one of spiral/roadrunner-worker[v2.0.3], spiral/goridge[2.4.1, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.6.4] | install one of spiral/goridge[v2.0.4, ..., v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.2] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.1] | install one of spiral/goridge[2.4.0, ..., v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/roadrunner[v1.6.1] | install one of spiral/goridge[v2.3.0, ..., v2.4.5, v3.0.0-beta2, ..., v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/php-grpc[v1.0.8] | install one of spiral/php-grpc[v1.1.0, v1.1.1, v1.2.0], spiral/roadrunner[v1.2.0, ..., v1.9.2], spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/php-grpc[v1.0.7] | install one of spiral/php-grpc[v1.1.0, v1.1.1, v1.2.0], spiral/roadrunner[v1.2.0, ..., v1.9.2], spiral/goridge[2.4.0, ..., v2.4.5, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/php-grpc[v1.0.6] | install one of spiral/roadrunner[v1.2.0, ..., v1.9.2], spiral/goridge[2.4.0, ..., v2.4.5, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/roadrunner[v1.6.2] | install one of spiral/goridge[2.4.0, ..., v2.4.5, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.0], spiral/roadrunner[v1.5.3] | install one of spiral/goridge[v2.3.2, ..., v2.4.5, v3.0.0-beta2, ..., v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.0], spiral/roadrunner[v1.6.2] | install one of spiral/goridge[2.4.0, ..., v2.4.5, v3.0.0-beta3, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.0], spiral/roadrunner[v1.6.3] | install one of spiral/goridge[2.4.1, ..., v2.4.5, v3.0.0-beta3, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Root composer.json requires spiral/roadrunner-laravel ^4.0 -> satisfiable by spiral/roadrunner-laravel[v4.0.0, v4.0.1].
    - Root composer.json requires spiral/php-grpc ^1.0 -> satisfiable by spiral/php-grpc[v1.0.0, ..., v1.5.0].
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.3], spiral/roadrunner[v1.8.0] | install one of spiral/goridge[2.4.0, v2.4.3, v2.4.4, v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/roadrunner[v1.6.4] | install one of spiral/goridge[v2.3.2, ..., v2.4.5, v3.0.0-beta2, ..., v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.6.4] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.2], spiral/roadrunner[v1.3.7] | install one of spiral/goridge[v2.1.0, ..., v2.4.5, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/roadrunner[v1.6.4] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.1], spiral/roadrunner[v1.6.3] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.0], spiral/roadrunner[v1.7.0] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[v2.0.0], spiral/roadrunner[v1.6.4] | install one of spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.0, v3.0.1] (conflict analysis result)
    - Conclusion: don't install one of spiral/roadrunner-worker[dev-master], spiral/roadrunner-laravel[v4.0.0] | install one of spiral/php-grpc[v1.1.0, v1.1.1, v1.2.0], spiral/roadrunner[v1.4.0, ..., v1.9.2], spiral/roadrunner-worker[v2.0.1, v2.0.2, v2.0.3], spiral/goridge[v2.4.2, v2.4.3, v2.4.4, v2.4.5, v3.0.0-beta4, v3.0.0, v3.0.1] (conflict analysis result)
    - spiral/roadrunner-worker 2.1.x-dev is an alias of spiral/roadrunner-worker dev-master and thus requires it to be installed too.
    - spiral/roadrunner-laravel v4.0.0 requires spiral/roadrunner-worker ^2.0 -> satisfiable by spiral/roadrunner-worker[v2.0.0, ..., 2.1.x-dev (alias of dev-master)].
    - spiral/roadrunner-worker dev-master requires spiral/goridge ^3.0 -> satisfiable by spiral/goridge[v3.0.0-beta1, ..., 3.1.x-dev (alias of dev-master)].
    - spiral/roadrunner-worker[v2.0.0, ..., v2.0.1] require spiral/goridge >=3.0 -> satisfiable by spiral/goridge[v3.0.0-beta1, ..., 3.1.x-dev (alias of dev-master)].
    - Conclusion: don't install one of spiral/goridge[v2.0.0], spiral/roadrunner-worker[v2.0.2] | install one of spiral/goridge[v3.0.0, v3.0.1] (conflict analysis result)
    - spiral/goridge 3.1.x-dev is an alias of spiral/goridge dev-master and thus requires it to be installed too.
    - You can only install one version of a package, so only one of these can be installed: spiral/goridge[dev-master, v2.0.0, ..., v2.4.5, v3.0.0-beta1, ..., v3.0.1].
    - spiral/roadrunner v1.5.1 requires spiral/goridge ^2.0 -> satisfiable by spiral/goridge[v2.0.0, ..., v2.4.5].
    - Conclusion: don't install spiral/goridge v2.0.1 (conflict analysis result)`

**Comment by wolfy-j** [comment]
PHP-GRPC is currently a separate build. We will merge GRPC into core in upcoming releases to make it possible to use it in Laravel.

**Comment by xuqihua** [comment]
> Currently PHP-GRPC is a separate build. We will merge GRPC into core in upcoming releases to make it possible to use it in Laravel.

Thanks!

**Comment by lanphan** [comment]
@wolfy-j ,
Any update on this issue? Currently I'm trying Laravel with Roadrunner, and my main focus is be able to run grpc in Laravel
