### ISSUE TITLE
Laravel Octane

### ISSUE THREAD

**Issue by vigneshgurusamy** [spiral/roadrunner-laravel#39]
Laravel has released first party package [octane](https://laravel.com/docs/8.x/octane) to support Roadrunner.

Do we need to migrate to octane on going forward?

**Comment by tarampampam** [comment]
Hi @vigneshgurusamy, thanks for your question!

Octane does the same thing as this package. This package still supports fresh laravel versions and we have no plans to abandon it.

So, my answer - you must decide for yourself. If you need sugar from the octane package or you want to have an option to switching between RR and Swoolie - migration makes sense. If not - you can continue using this package :)

**Comment by tarampampam** [comment]
Can I close this issue?

**Comment by vigneshgurusamy** [comment]
Thanks for the clarification :)
