### ISSUE TITLE
Improve bridge performance and reduce memory consumption

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner-laravel#5]
At the moment most of the extensions work using `symfony/psr-http-message-bridge` which converts PSR-7 request/response into Symfony/HttpKernel.

The RoadRunner worker exposes low level API to access the incoming request data in the form of an array.

https://github.com/spiral/roadrunner-http/blob/master/src/HttpWorker.php

Essentially, it makes it possible to skip the PSR-7 implementation as whole and map data directly to Symfony Request/Response. 

Benefits:
- lower memory consumption (you can reuse Symfony requests)
- higher performance 
- less dependencies

**Comment by wolfy-j** [comment]
P.S. we can also add “native” adjective after this patch.

**Comment by tarampampam** [comment]
Hm, ok, a will think about it

**Comment by tarampampam** [comment]
About one year later...

I have attempted to implement skipping PSR-7 request creation during the work under the fresh package version, and in two words - it's not worth the gamble. Reasons:

- Low-level API usage requires a lot of code copy-pasting with minimal changes
- Copy-pasted code need to be supported
- The conversion between PSR-7 and Symfony requests is [really cheap](https://github.com/symfony/psr-http-message-bridge/blob/26068fa40d91305529cb168997c0b528bb6eef07/Factory/HttpFoundationFactory.php#L45-L84)

@wolfy-j can I close this issue?
