### ISSUE TITLE
Laravel Telescope shows its own http requests in the Requests list.

### ISSUE THREAD

**Issue by darakanoit** [spiral/roadrunner-laravel#53]
### Is your feature request related to a problem?
Yes
![image](https://user-images.githubusercontent.com/44018664/125186268-3421ff80-e24b-11eb-9f19-a662c4c3f6c0.png)
### Describe the solution you'd like
The solution from https://github.com/avto-dev/roadrunner-laravel/issues/23 helped, but I would like it to work out of the box. Is it possible to examine the behavior of Laravel Octane relative to the Laravel Telescope?
## Additional context
"laravel/telescope": "^4.5",
 "laravel/framework": "^8.40",
  "spiral/roadrunner-laravel": "^5.0"
  php:8.0.7-cli
  spiralscout/roadrunner:2.2.1

**Comment by darakanoit** [comment]
The solution from https://github.com/avto-dev/roadrunner-laravel/issues/23 only hides these requests from the list, but they are still being written to the database ..

**Comment by tarampampam** [comment]
Hi @darakanoit, and thanks for your issue!

Could you please test changes in #54? If you confirm that all works fine - these changes will be released shortly!

**Comment by tarampampam** [comment]
v5.2.0 with Telescope supporting [has been released](https://github.com/spiral/roadrunner-laravel/releases/tag/v5.2.0) 🎉
