### ISSUE TITLE
How to fix unable to connect to default worker?

### ISSUE THREAD

**Issue by ant100** [spiral/roadrunner-laravel#6]
I installed the composer package and followed instructions. But after running 

$ rr -c ./.rr.yaml serve -d

I get the following error:

Error: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1

Is it something wrong with the ./vendor/bin/rr-worker file? I'm on windows.

**Comment by tarampampam** [comment]
It looks like `echo`, `print`, `printf`, `dump`, `dd` or similar functions is used in your application

**Comment by tarampampam** [comment]
@ant100 issue can be closed?

**Comment by ant100** [comment]
Hi yes this can be closed, I'm still setting this up though. If I continue to have issues with this could I comment again?

**Comment by tarampampam** [comment]
Yes, sure!
