### ISSUE TITLE
Использование воркеров под разные плагины RR

### ISSUE THREAD

**Issue by butschster** [spiral/roadrunner-laravel#61]
Насколько я понимаю сейчас RR может работать только с HTTP и если, допустим, мне необходимо добавить TCP плагин, то мне необходимо для него использовать альтернытивный воркер со своим обработчиком TCP запросов

**Comment by tarampampam** [comment]
It depends on your plugin code, of course. Issue can be closed?

**Comment by butschster** [comment]
Нет. Скорее всего пакет для Laravel необходимо будет расширять, например добавить воркеры для очередей и стоит посмотреть в сторону разделения воркеров на разные типы. Сейчас есть только https://github.com/spiral/roadrunner-laravel/blob/master/src/Worker.php, скорее всего он должен стать HttpWorker и добавиться еще QueueWorker и т.д.

**Comment by tarampampam** [comment]
Please, use English for your messages (this is important for the community).

When different types of workers will be implemented - existing classes will be renamed respectively :smiley:

**Comment by butschster** [comment]
> Please, use English for your messages (this is important for the community).
> 
> When different types of workers will be implemented - existing classes will be renamed respectively 😃

Right now we have jobs, http

**Comment by tarampampam** [comment]
At this moment this package supports only HTTP workers (and nothing more). If you want to:

- Use custom TCP plugin on the RR side - implement your custom worker on the PHP side for him
- Use your custom HTTP worker - implement it (you can extend the existing worker code, of course) and use
- Suggest implementing something else - explain it, and if makes the sense - we will implement it!

Sorry, but at this moment I can't understand what exactly you want :(

**Comment by butschster** [comment]
В общем эта issue была для @SerafimArts чтобы подумать как быть в том случае, если разработчик захочет не только HTTP использовать, а еще Jobs. В будущем может появиться еще  вариации воркеров и необходимо предусмотреть возможность расширения, т.к. сейчас пакет завязан исключительно на HTTP воркер. Чтобы расширить поведение мне сейчас пришлось копировать код и добавлять туда дополнительную реализацию. Пример можно посмотреть здесь https://github.com/buggregator/app/blob/feature/roadrunner/bin/rr-worker#L71

**Comment by tarampampam** [comment]
Oh, ok, I think I understand you now :) Can I close this issue and continue our discussion in #62?

**Comment by tarampampam** [comment]
ping @butschster

**Comment by butschster** [comment]
> Oh, ok, I think I understand you now :) Can I close this issue and continue our discussion in #62?

I think yes, you can close the issue.
