### ISSUE TITLE
State resetting for the tighten/ziggy package

### ISSUE THREAD

**Issue by butschster** [spiral/roadrunner-laravel#63]
Сейчас при после пары обновлений страницы при использовании Jetstream с InertiaJs появляется ошибка.

```
Uncaught ReferenceError: Ziggy is not defined
Uncaught (in promise) ReferenceError: route is not defined
```

Причина ошибки связана с пакетом `tightenco/ziggy` в классе `Tightenco\Ziggy\BladeRouteGenerator`.

Сброс состояния в `BladeRouteGenerator::$generated = false` решает проблему.

**Comment by butschster** [comment]
Чуть позже могу залить PR

**Comment by SerafimArts** [comment]
PR с чем? Этот пакет не имеет ничего общего с `tightenco/ziggy`.

**Comment by butschster** [comment]
> PR с чем? Этот пакет не имеет ничего общего с `tightenco/ziggy`.

Ну так этот пакет входит в состав [Jetstream](https://jetstream.laravel.com), это поддержка для этого пакета

**Comment by tarampampam** [comment]
[laravel/jetstream](https://github.com/laravel/jetstream) does [not](https://github.com/laravel/jetstream/blob/a24cddce5e158c743723cc04f9b8d3194f62aab3/composer.json#L16-L22) requires [tighten/ziggy](https://github.com/tighten/ziggy) (or this is a "hidden" dependency?). Anyway, `ziggy` looks like a popular package, and if you need in "resetter" - we can implement it :smiley:

**Comment by tarampampam** [comment]
ping @butschster

**Comment by butschster** [comment]
> [laravel/jetstream](https://github.com/laravel/jetstream) does [not](https://github.com/laravel/jetstream/blob/a24cddce5e158c743723cc04f9b8d3194f62aab3/composer.json#L16-L22) requires [tighten/ziggy](https://github.com/tighten/ziggy) (or this is a "hidden" dependency?). Anyway, `ziggy` looks like a popular package, and if you need in "resetter" - we can implement it 😃

Yes, `laravel/jetstream` has a hidden dependency on `tighten/ziggy` (You can find it here https://github.com/laravel/jetstream/blob/2.x/src/Console/InstallCommand.php#L283). As I understand this package is quite popular among Laravel arisans. It would be a good decision to add support for this package.
