### ISSUE TITLE
Can I use RR to get messages from websockets?

### ISSUE THREAD

**Issue by zolotov88** [spiral/roadrunner-laravel#7]
[Swoole](https://github.com/swooletw/laravel-swoole) can work with Socket.io. 
Can I use RR to get messages from websockets in my Laravel app?

**Comment by wolfy-j** [comment]
Can you clarify "get messages from websockets"? Sure you can, but I'm not quite sure I've got your question. https://spiral.dev/docs/broadcast-websockets

**Comment by tarampampam** [comment]
Closed due inactivity

**Comment by zolotov88** [comment]
> Can you clarify "get messages from websockets"? Sure you can, but I'm not quite sure I've got your question. https://spiral.dev/docs/broadcast-websockets

I do not understand how to use it in Laravel. This instructions is very simple: [https://github.com/swooletw/laravel-swoole/wiki/7.-Websocket](https://github.com/swooletw/laravel-swoole/wiki/7.-Websocket). Can I do something like this with RR? How can  I do it?
```php
Websocket::on('event', 'Controller@action'); 
```

**Comment by wolfy-j** [comment]
You can not _accept_ WebSocket commands in RR without custom Golang code yet.
