### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nitrogenium** [spiral/roadrunner-laravel#8]
## Describe the bug

If you request a page that does not exist (error 404), there is a memory leak.

And after several such requests Worker is closed because the memory consumption limit is exceeded.

### Steps to reproduce the behavior:

It is easy to reproduce. Create a new clean Laravel 7 project, launch it under RR (with unlimited number of requests for Worker) and make a hundred calls to a page that does not exist and watch the log.

**Comment by tarampampam** [comment]
I will try to reproduce this soon as possible

**Comment by tarampampam** [comment]
I cannot reproduce behavior, described by you. Can you attach versions of `rr`, `php`, current package, `./config/roadrunner.php` and roadrunner daemon configs?

**Comment by nitrogenium** [comment]
https://github.com/nitrogenium/Demo404memleaks

**Comment by nitrogenium** [comment]
This is a clean Laravel 7 with a demonstration of the behavior.

**Comment by tarampampam** [comment]
Local tests (your example without any changes):

### 404 page

![leaks404](https://user-images.githubusercontent.com/7326800/87139171-f8133200-c2b8-11ea-89c6-793a1a94b165.png)

```
...
INFO[0173] 172.25.0.1 {10.1ms} 404 GET http://localhost:4001/404 
INFO[0173] 172.25.0.1 {9.67ms} 404 GET http://localhost:4001/404 
INFO[0173] 172.25.0.1 {9.58ms} 404 GET http://localhost:4001/404 
INFO[0173] 172.25.0.1 {9.51ms} 404 GET http://localhost:4001/404 
ERRO[0173] worker.119 max allowed memory reached (64MB) 
INFO[0173] 172.25.0.1 {9.60ms} 404 GET http://localhost:4001/404 
INFO[0173] 172.25.0.1 {201ms} 404 GET http://localhost:4001/404 
INFO[0173] 172.25.0.1 {1.26ms} 404 GET http://localhost:4001/404 
INFO[0173] 172.25.0.1 {1.09ms} 404 GET http://localhost:4001/404 
INFO[0173] 172.25.0.1 {1.01ms} 404 GET http://localhost:4001/404 
...
```

### Regular page

![noleaks](https://user-images.githubusercontent.com/7326800/87139107-e0d44480-c2b8-11ea-95b3-442d2bb01515.png)

```
...
INFO[0032] 172.26.0.1 {2.99ms} 200 GET http://localhost:4001/ 
INFO[0032] 172.26.0.1 {3.37ms} 200 GET http://localhost:4001/ 
INFO[0032] 172.26.0.1 {3.11ms} 200 GET http://localhost:4001/ 
INFO[0032] 172.26.0.1 {2.95ms} 200 GET http://localhost:4001/ 
INFO[0032] 172.26.0.1 {2.89ms} 200 GET http://localhost:4001/ 
INFO[0032] 172.26.0.1 {2.90ms} 200 GET http://localhost:4001/ 
INFO[0032] 172.26.0.1 {3.21ms} 200 GET http://localhost:4001/ 
INFO[0032] 172.26.0.1 {3.11ms} 200 GET http://localhost:4001/ 
...
```

**Comment by nitrogenium** [comment]
That's right!
This is it:

INFO[0173] 172.25.0.1 {9.51ms} 404 GET http://localhost:4001/404 
ERRO[0173] worker.119 max allowed memory reached (64MB) 
INFO[0173] 172.25.0.1 {9.60ms} 404 GET http://localhost:4001/404

**Comment by tarampampam** [comment]
Интереснее почему этого не происходит на "регулярном" роуте

**Comment by wolfy-j** [comment]
It could be some event or log attached to the missed route.

**Comment by tarampampam** [comment]
Dockstation shows wrong stats: https://github.com/DockStation/dockstation/issues/122#issuecomment-397868562

Regular page processed with really low memory leak (~5 MiB per 10000 requests)

But large memory leak with 404 error confirmed, and it seems like leak on framework side (not RR)

**Comment by tarampampam** [comment]
Try to change in `composer.json` next lines:

```diff
diff --git a/composer.json b/composer.json
index 89d201f..f987577 100644
--- a/composer.json
+++ b/composer.json
@@ -30,7 +30,9 @@
     },
     "extra": {
         "laravel": {
-            "dont-discover": []
+            "dont-discover": [
+                "facade/ignition"
+            ]
         }
     },
     "autoload": {
```

Execute `composer dump` and try to reproduce behavior described by you.

Anyway, `facade/ignition` is dev-dependency, and on production environment all must be fine.

**Comment by nitrogenium** [comment]
Yes, the cause of the leak is clear now. It's facade/ignition. Thank you!

**Comment by wolfy-j** [comment]
Does it make sense to report the issue to them?
