### ISSUE TITLE
Why do I test according to this example? QPS is very low. Where is it not configured

### ISSUE THREAD

**Issue by pretty66** [spiral/roadrunner-laravel#80]
Why is QPS very low according to this example? Is there a problem with my configuration

- php7.4
- roadrunner: 2.7
## config
![image](https://user-images.githubusercontent.com/21053373/149871235-0ab5b9de-294b-4526-892f-9ca468570bf5.png)
## test
![image](https://user-images.githubusercontent.com/21053373/149870892-984e7774-5d85-479c-9d5d-9a117a9a3e62.png)

**Comment by tarampampam** [comment]
Hi @pretty66! How can I reproduce described behavior? Could you please make a repository with a demonstration?

**Comment by pretty66** [comment]
> Hi @pretty66! How can I reproduce described behavior? Could you please make a repository with a demonstration?

Yes, this is my test code：[test code](https://github.com/pretty66/roadrunner-laravel-test)

**Comment by tarampampam** [comment]
```diff
diff --git a/.env.example b/.env.example
index b7becba..ba43d82 100644
--- a/.env.example
+++ b/.env.example
@@ -19,7 +19,7 @@ BROADCAST_DRIVER=log
 CACHE_DRIVER=file
 FILESYSTEM_DRIVER=local
 QUEUE_CONNECTION=sync
-SESSION_DRIVER=file
+SESSION_DRIVER=array
 SESSION_LIFETIME=120
 
 MEMCACHED_HOST=127.0.0.1
```

Before:

```bash
$ wrk -d 5 http://127.0.0.1:1876/info
Running 5s test @ http://127.0.0.1:1876/info
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   105.46ms  158.05ms 598.22ms   80.95%
    Req/Sec   322.81    246.03     1.08k    67.74%
  3071 requests in 5.00s, 3.08MB read
Requests/sec:    613.66
Transfer/sec:    630.44KB
```

After:

```bash
$ wrk -d 5 http://127.0.0.1:1876/info
Running 5s test @ http://127.0.0.1:1876/info
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.95ms    1.23ms  28.91ms   94.04%
    Req/Sec     1.29k    76.95     1.43k    74.00%
  12811 requests in 5.00s, 12.85MB read
Requests/sec:   2561.09
Transfer/sec:      2.57MB
```

Related issue: #23 ([one more example](https://github.com/tarampampam/laravel-roadrunner-in-docker))

@pretty66  This issue can be closed?

**Comment by pretty66** [comment]
Thank you. The issue can be closed
